Repository improbable/superset, pull requests merged in 2020-07, with the labels that each got.

#1 CHINF-1597 add customer tag filter in detail page
  superset-frontend/src/chart/chartAction.js
  superset-frontend/src/explore/components/controls/DateFilterControl.jsx
  superset-frontend/src/visualizations/FilterBox/FilterBox.jsx
  superset/translations/zh/LC_MESSAGES/messages.json
  superset/translations/zh/LC_MESSAGES/messages.po
Labels: jira/CHINF, size/XXL

#2 add premerge ci
  .buildkite/premerge.definition.yaml
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/S

#5 Chinf-1664 change pivot table html format to be convenient
  superset/views/core.py
  superset/views/utils.py
Labels: jira/no-ticket, size/M

#7 CHINF-1660 The icon link should jump to console on billing page
  superset-frontend/src/explore/components/controls/DateFilterControl.jsx
  superset/templates/appbuilder/navbar.html
  superset/templates/appbuilder/navbar_right.html
Labels: jira/CHINF, size/M

#13 remove publish status and fav star from dashboard status
  superset-frontend/spec/javascripts/dashboard/components/Header_spec.jsx
  superset-frontend/src/dashboard/components/Header.jsx
Labels: jira/no-ticket, size/M

#15 update Chinese
  superset/translations/zh/LC_MESSAGES/messages.json
Labels: jira/no-ticket, size/XS

#14 CHINF-1688: change pivot table style
  superset/translations/zh/LC_MESSAGES/messages.json
  superset/translations/zh/LC_MESSAGES/messages.po
  superset/views/utils.py
Labels: jira/CHINF, size/M

#16 allow import slug
  superset/models/dashboard.py
Labels: jira/no-ticket, size/XS

#18 smaller dashboard title
  superset-frontend/src/dashboard/components/Header.jsx
Labels: jira/CHINF, size/XS
