Repository improbable/superset, pull requests merged in 2020-08, with the labels that each got.

#19 CHINF-1700 hide download page for normal user
  superset/views/core.py
Labels: jira/CHINF, size/XS

#20 Chinf 1701
  superset-frontend/src/dashboard/components/SliceHeader.jsx
  superset-frontend/src/dashboard/components/SliceHeaderControls.jsx
  superset-frontend/src/dashboard/stylesheets/dashboard.less
  superset/views/core.py
Labels: jira/no-ticket, size/S

#21 CHINF-1658 translate all into chinese
  .buildkite/premerge.steps.yaml
  superset/views/utils.py
Labels: jira/CHINF, size/XS

#22 CHINF-1713 add csv btn
  superset-frontend/package-lock.json
  superset-frontend/package.json
  superset/views/core.py
Labels: jira/CHINF, size/XL

#23 CHINF-1708 format number to ,.2f
  superset/views/utils.py
Labels: jira/CHINF, size/XS

#24 CHINF-1717 translate menu
  superset/config.py
  superset/translations/zh/LC_MESSAGES/messages.json
Labels: jira/CHINF, size/S

#25 translate
  superset/translations/zh/LC_MESSAGES/messages.json
Labels: jira/no-ticket, size/XS

#26 CHINF-1728 translate date dropdown button title
  superset-frontend/src/explore/components/controls/DateFilterControl.jsx
Labels: jira/CHINF, size/XS

#27 CHINF-1730 remove maximum and download as image menu
  superset-frontend/src/dashboard/components/SliceHeaderControls.jsx
Labels: jira/CHINF, size/XS

#28 bump to 0.37
  CHANGELOG.md
  superset/db_engine_specs/base.py
  superset/views/database/forms.py
  superset/views/database/views.py
  superset/viz.py
  tests/viz_tests.py
Labels: jira/no-ticket, size/M

#29 add Makefile
  Makefile
Labels: jira/no-ticket, size/XS

#31 CHINF-1728 Bad layout for filter window
  superset-frontend/src/explore/components/controls/DateFilterControl.jsx
  superset-frontend/src/explore/components/controls/DateFilterControl.less
Labels: jira/CHINF, size/S

#32 create docker file to build artifact for release, update make file
  Dockerfile_buildartifact
  Makefile
Labels: jira/no-ticket, size/M

#33 bump legacy-preset-chart-nvd3 version
  superset-frontend/package-lock.json
  superset-frontend/package.json
Labels: jira/no-ticket, size/M
